name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [21-jdk]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x gradlew
      - run: ./gradlew build --stacktrace --warning-mode fail
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts ${{ matrix.java }}
          path: build/libs/