name: Snapshot check
on:
  schedule:
    - cron: "*/60 6-19 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  check:
    env:
      LATEST_VERSION: ${{ vars.LATEST_MC_VERSION }}

    outputs:
      is_new: ${{ fromJson(steps.check.outputs.result).is_new }}
      old_version: ${{ toJson(fromJson(steps.check.outputs.result).old_version) }}
      new_version: ${{ toJson(fromJson(steps.check.outputs.result).new_version) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Version Manifest
        id: version_manifest
        run: echo "latest_snapshot=$(wget -O - https://piston-meta.mojang.com/mc/game/version_manifest_v2.json | jq -r .latest.snapshot)" >> $GITHUB_OUTPUT
      - name: Check latest snapshot
        id: check
        uses: actions/github-script@v7
        env:
          NEW_LATEST_VERSION: ${{ steps.version_manifest.outputs.latest_snapshot }}
        with:
          script: |
            function getInfo(name) {
              var type = "";
              var april = false;
              if (/^\d+\.\d+(\.\d+)?$/.test(name)) {
                type = "release";
              } else if (/^\d{2}w\d{2}[a-z]$/.test(name)) {
                type = "snapshot";
              } else if (/^\d+\.\d+(.\d+)?-(pre|rc)\d+$/.test(name) || /^\d+\.\d+.\d+-rc\d+$/.test(name)) {
                type = "pre";
              } else {
                // If it doesn't match anything guess that it's an april fools release
                type = "snapshot";
                april = true;
              }
              return {type: type, april: april, version: name}
            }

            const latestSnapshot = process.env.NEW_LATEST_VERSION

            const newVersionInfo = getInfo(latestSnapshot);
            const oldVersion = process.env.LATEST_VERSION;
            const oldVersionInfo = getInfo(oldVersion);

            if (process.env.LATEST_VERSION === latestSnapshot) {
              core.info("No new snapshots have been released since " + process.env.LATEST_VERSION)
              return {old_version: oldVersionInfo, new_version: newVersionInfo, is_new: false};
            }

            core.info("Found new snapshot: " + latestSnapshot)
            return {old_version: oldVersionInfo, new_version: newVersionInfo, is_new: true};  

  run-update:
    runs-on: ubuntu-latest
    needs:
      - check
    if: ${{ always() && !cancelled() && !failure() && needs.check.result == 'success' && needs.check.outputs.is_new == 'true' }}
    env:
      TARGET_VERSION: ${{ vars.TARGET_MC_VERSION }}
    steps:
      - name: Run update workflow
        id: update
        uses: actions/github-script@v7
        env:
          OLD_VERSION_INFO: ${{ needs.check.outputs.old_version }}
          NEW_VERSION_INFO: ${{ needs.check.outputs.new_version }}
        with:
          script: |
            const oldVersionInfo = JSON.parse(process.env.OLD_VERSION_INFO);
            const newVersionInfo = JSON.parse(process.env.NEW_VERSION_INFO);
            
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "new_version.yml",
              ref: "master",
            });

      - name: Store Latest Version
        uses: octokit/request-action@v2.3.0
        with:
          route: PATCH /repos/{repo}/actions/variables/{name}
          repo: ${{ github.repository }}
          name: LATEST_MC_VERSION
          value: "\"${{ fromJson(needs.check.outputs.new_version).version }}\""
        env:
          GITHUB_TOKEN: ${{ secrets.VARIABLES_TOKEN }}
